package com.hlayan.forexrate

enum class Currencies(val flagEmoji: String, val fullName: String) {
    AUD("\ud83c\udde6\ud83c\uddfa", "Australian Dollar"),
    BDT("\ud83c\udde7\ud83c\udde9", "Bangladesh Taka"),
    BND("\ud83c\udde7\ud83c\uddf3", "Brunei Dollar"),
    BRL("\ud83c\udde7\ud83c\uddf7", "Brazilian Real"),
    CAD("\ud83c\udde8\ud83c\udde6", "Canadian Dollar"),
    CHF("\ud83c\uddeb\ud83c\uddf7", "Swiss Franc"),
    CNY("\ud83c\udde8\ud83c\uddf3", "Chinese Yuan"),
    CZK("\ud83c\udde8\ud83c\uddff", "Czech Koruna"),
    DKK("\ud83c\udde9\ud83c\uddf0", "Danish Krone"),
    EGP("\ud83c\uddea\ud83c\uddec", "Egyptian Pound"),
    EUR("\ud83c\uddea\ud83c\uddfa", "Euro"),
    GBP("\ud83c\uddec\ud83c\udde7", "Pound Sterling"),
    HKD("\ud83c\udded\ud83c\uddf0", "Hong Kong Dollar"),
    IDR("\ud83c\uddee\ud83c\udde9", "Indonesian Rupiah"),
    ILS("\ud83c\uddee\ud83c\uddf1", "Israeli Shekel"),
    INR("\ud83c\uddee\ud83c\uddf3", "Indian Rupee"),
    JPY("\ud83c\uddef\ud83c\uddf5", "Japanese Yen"),
    KES("\ud83c\uddf0\ud83c\uddea", "Kenya Shilling"),
    KHR("\ud83c\uddf0\ud83c\udded", "Cambodian Riel"),
    KRW("\ud83c\uddf0\ud83c\uddf7", "Korean Won"),
    KWD("\ud83c\uddf0\ud83c\uddfc", "Kuwaiti Dinar"),
    LAK("\ud83c\uddf1\ud83c\udde6", "Lao Kip"),
    LKR("\ud83c\uddf1\ud83c\uddf0", "Sri Lankan Rupee"),
    MMK("\ud83c\uddf2\ud83c\uddf2", "Myanmar Kyat"),
    MYR("\ud83c\uddf2\ud83c\uddfe", "Malaysian Ringgit"),
    NOK("\ud83c\uddf3\ud83c\uddf4", "Norwegian Kroner"),
    NPR("\ud83c\uddf3\ud83c\uddf5", "Nepalese Rupee"),
    NZD("\ud83c\uddf3\ud83c\uddff", "New Zealand Dollar"),
    PHP("\ud83c\uddf5\ud83c\udded", "Philippines Peso"),
    PKR("\ud83c\uddf5\ud83c\uddf0", "Pakistani Rupee"),
    RSD("\ud83c\uddf7\ud83c\uddf8", "Serbian Dinar"),
    RUB("\ud83c\uddf7\ud83c\uddfa", "Russian Rouble"),
    SAR("\ud83c\uddf8\ud83c\udde6", "Saudi Arabian Riyal"),
    SEK("\ud83c\uddf8\ud83c\uddea", "Swedish Krona"),
    SGD("\ud83c\uddf8\ud83c\uddec", "Singapore Dollar"),
    THB("\ud83c\uddf9\ud83c\udded", "Thai Baht"),
    USD("\ud83c\uddfa\ud83c\uddf8", "United State Dollar"),
    VND("\ud83c\uddfb\ud83c\uddf3", "Vietnamese Dong"),
    ZAR("\ud83c\uddff\ud83c\udde6", "South Africa Rand")
}